export enum GroupActionTypes {
  GET_GROUP = '[GROUP_PAGE] GET GROUP',
  GET_GROUP_SUCCESSFUL = '[GROUP_PAGE] GET GROUP SUCCESSFUL',
  GET_GROUP_FAILED = '[GROUP_PAGE] GET GROUP FAILED',

  CREATE_GROUP = '[GROUP_PAGE] CREATE GROUP',
  CREATE_GROUP_SUCCESSFUL = '[GROUP_PAGE] CREATE GROUP SUCCESSFUL',
  CREATE_GROUP_FAILED = '[GROUP_PAGE] CREATE GROUP FAILED',

  DELETE_GROUP = '[GROUP_PAGE] DELETE GROUP',
  DELETE_GROUP_SUCCESSFUL = '[GROUP_PAGE] DELETE GROUP SUCCESSFUL',
  DELETE_GROUP_FAILED = '[GROUP_PAGE] DELETE GROUP FAILED',

  UPDATE_GROUP = '[GROUP_PAGE] UPDATE GROUP',
  UPDATE_GROUP_SUCCESSFUL = '[GROUP_PAGE] UPDATE GROUP SUCCESSFUL',
  UPDATE_GROUP_FAILED = '[GROUP_PAGE] UPDATE GROUP FAILED'
}
