export enum GroupActionTypes {
  GET_GROUP = '[GROUP_PAGE] GET GROUP',
  GET_GROUP_SUCCESSFUL = '[GROUP_PAGE] GET GROUP SUCCESSFUL',
  GET_GROUP_FAILED = '[GROUP_PAGE] GET GROUP FAILED',

  CREATE_GROUP = '[GROUP_PAGE] CREATE GROUP',
  CREATE_GROUP_SUCCESSFUL = '[GROUP_PAGE] CREATE GROUP SUCCESSFUL',
  CREATE_GROUP_FAILED = '[GROUP_PAGE] CREATE GROUP FAILED'
}
