export enum PeopleActionTypes {
  GET_PEOPLE = '[PEOPLE_PAGE] GET PEOPLE',
  GET_PEOPLE_SUCCESSFUL = '[PEOPLE_PAGE] GET PEOPLE SUCCESSFUL',
  GET_PEOPLE_FAILED = '[PEOPLE_PAGE] GET PEOPLE FAILED',

  UPDATE_PEOPLE = '[PEOPLE_PAGE] UPDATE PEOPLE',
  UPDATE_PEOPLE_SUCCESSFUL = '[PEOPLE_PAGE] UPDATE PEOPLE SUCCESSFUL',
  UPDATE_PEOPLE_FAILED = '[PEOPLE_PAGE] UPDATE PEOPLE FAILED'
}
