export enum PeopleMessageActionTypes {
  GET_PEOPLE_MESSAGE = '[PEOPLE_MESSAGE_PAGE] GET PEOPLE MESSAGE',
  GET_PEOPLE_MESSAGE_SUCCESSFUL = '[PEOPLE_MESSAGE_PAGE] GET PEOPLE MESSAGE SUCCESSFUL',
  GET_PEOPLE_MESSAGE_FAILED = '[PEOPLE_MESSAGE_PAGE] GET PEOPLE MESSAGE FAILED',

  SEND_PEOPLE_MESSAGE = '[PEOPLE_MESSAGE_PAGE] SEND PEOPLE MESSAGE',
  SEND_PEOPLE_MESSAGE_SUCCESSFUL = '[PEOPLE_MESSAGE_PAGE] SEND PEOPLE MESSAGE SUCCESSFUL',
  SEND_PEOPLE_MESSAGE_FAILED = '[PEOPLE_MESSAGE_PAGE] SEND PEOPLE MESSAGE FAILED',

  UPDATE_PEOPLE_MESSAGE = '[PEOPLE_MESSAGE_PAGE] UPDATE PEOPLE MESSAGE',
  UPDATE_PEOPLE_MESSAGE_SUCCESSFUL = '[PEOPLE_MESSAGE_PAGE] UPDATE PEOPLE MESSAGE SUCCESSFUL',
  UPDATE_PEOPLE_MESSAGE_FAILED = '[PEOPLE_MESSAGE_PAGE] SEND UPDATE MESSAGE FAILED'
}
