export enum ProfileActionTypes {
  GET_PROFILE = '[PROFILE_PAGE] GET PROFILE',
  GET_PROFILE_SUCCESSFUL = '[PROFILE_PAGE] GET PROFILE SUCCESSFUL',
  GET_PROFILE_FAILED = '[PROFILE_PAGE] GET PROFILE FAILED'
}
