export enum ProfileActionTypes {
  GET_PROFILE = '[PROFILE_PAGE] GET PROFILE',
  GET_PROFILE_SUCCESSFUL = '[PROFILE_PAGE] GET PROFILE SUCCESSFUL',
  GET_PROFILE_FAILED = '[PROFILE_PAGE] GET PROFILE FAILED',

  UPDATE_PROFILE_NAME = '[PROFILE_PAGE] UPDATE PROFILE NAME',
  UPDATE_PROFILE_NAME_SUCCESSFUL = '[PROFILE_PAGE] UPDATE PROFILE NAME SUCCESSFUL',
  UPDATE_PROFILE_NAME_FAILED = '[PROFILE_PAGE] UPDATE PROFILE NAME FAILED',

  LOGOUT_PROFILE = '[PROFILE_PAGE] LOGOUT PROFILE',
  LOGOUT_PROFILE_SUCCESSFUL = '[PROFILE_PAGE] LOGOUT PROFILE SUCCESSFUL',
  LOGOUT_PROFILE_FAILED = '[PROFILE_PAGE] LOGOUT PROFILE FAILED'
}
