export enum CustomCardActionTypes {
  GET_CUSTOM_CARD = '[YOUTUBE_PAGE] GET YOUTUBE CARD',
  CREATE_CUSTOM_CARD = '[YOUTUBE_PAGE] CREATE YOUTUBE CARD',
  DELETE_CUSTOM_CARD = '[YOUTUBE_PAGE] DELETE YOUTUBE CARD'
}
