export enum YoutubeCardActionTypes {
  ADD_YOUTUBE_CARD = '[YOUTUBE_PAGE] ADD YOUTUBE CARD',
  ADD_YOUTUBE_CARDS = '[YOUTUBE_PAGE] ADD YOUTUBE CARDS',
  CLEAR_YOUTUBE_CARDS = '[YOUTUBE_PAGE] CLEAR YOUTUBE CARD',
  SEARCH_QUERY_YOUTUBE_CARDS = '[YOUTUBE_PAGE] SEARCH QUERY YOUTUBE CARD',
  SEARCH_ON_PAGE_YOUTUBE_CARDS = '[YOUTUBE_PAGE] SEARCH ON PAGE YOUTUBE CARD'
}
