export enum YoutubeCardActionTypes {
  ADD_CARD = '[YOUTUBE_PAGE] ADD YOUTUBE CARD',
  ADD_CARDS = '[YOUTUBE_PAGE] ADD YOUTUBE CARDS',
  CLEAR = '[YOUTUBE_PAGE] CLEAR YOUTUBE CARD',
  SEARCH_QUERY = '[YOUTUBE_PAGE] SEARCH QUERY YOUTUBE CARD',
  SEARCH_ON_PAGE = '[YOUTUBE_PAGE] SEARCH YOUTUBE CARD'
}
